### ISSUE TITLE
Images not displaying in Gnome terminal

### ISSUE THREAD

**Issue by jeroendeswaef** [mrowa44/emojify#1]
Hi, 

On my system, not all characters are being rendered properly. Could it be due to the font?
I have the default font enabled (Monospace 12). The character encoding is UTF-8.
I'm using Ubuntu 14.04.2 LTS with the Gnome Terminal 3.6.2.

![image](https://cloud.githubusercontent.com/assets/164385/8888844/ae04ae5c-32bf-11e5-9904-276d456863b2.png)

**Comment by auscompgeek** [comment]
> images

There are no images, only characters.

What your *actual* problem is, for the characters that are showing as hex digits in boxes, is that you don't have the relevant font to display emoji. Since you're using a Linux distro, you'll want to install the Symbola font.

**Comment by zyphlar** [comment]
TTF available here: http://www.fonts2u.com/symbola.font

**Comment by auscompgeek** [comment]
@zyphlar Bad idea, you should install it from your distro's repos. Regardless, you should be linking Symbola's actual homepage, not some random font site.

**Comment by zyphlar** [comment]
@auscompgeek sure. His homepage seems to be on hiatus: http://users.teilar.gr/~g1951d/

**Comment by auscompgeek** [comment]
@zyphlar Ah, so it would seem. The Symbola zip seems to be gone from there as well. That's a shame.

**Comment by jordanarseno** [comment]
`sudo apt-get install ttf-ancient-fonts`
