### ISSUE TITLE
Rewrite to_emoji function to use something better than linear search

### ISSUE THREAD

**Issue by mrowa44** [mrowa44/emojify#14]
binary search for example

**Comment by GrenderG** [comment]
Should we close this? [Current execution time](https://docs.google.com/spreadsheets/d/1bTPSi6lFQQZEkEqbfhfFy9TqwAIOZC6tNww1ZTv3FSw/edit?usp=sharing) is great IMO.

**Comment by mrowa44** [comment]
👍
