### ISSUE TITLE
[Bug] Cannot display emoji with git log option 'less'

### ISSUE THREAD

**Issue by ooJerryLeeoo** [mrowa44/emojify#16]
This is what I got after run `git log --oneline --color | emojify | less`:

![less](https://cloud.githubusercontent.com/assets/20783502/24889807/cf019d3c-1e9e-11e7-8438-aafca67f8f99.png)

And this is what I got after I remove the `less` option:

![without less](https://cloud.githubusercontent.com/assets/20783502/24889800/c005e220-1e9e-11e7-81d8-ebb271f9b637.png)

**Comment by mrowa44** [comment]
Does it work if you use `less -r`?

**Comment by ooJerryLeeoo** [comment]
Oh, thanks :+1:, it works very well for me :grinning:
