### ISSUE TITLE
Skip/Ignore Existing Unicode Emoji Characters

### ISSUE THREAD

**Issue by haywirez** [mrowa44/emojify#17]
With `git log --oneline --color | emojify` and `🐛 Add React CSS Modules to .babelrc` as input, I'm getting an output of:

`ð Add React CSS Modules to .babelrc`

Instead of:

`🐛 Add React CSS Modules to .babelrc`

**Comment by GrenderG** [comment]
We are working in a new version where this issue is solved.

**Comment by GrenderG** [comment]
This issue has been solved [here](https://github.com/mrowa44/emojify/commit/3687df2de57e88ac9361676c3dd349c6a16f8f2c), sorry for any inconveniences.
