### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by SwampDolphin97** [mrowa44/emojify#19]
/usr/local/bin/emojify: line 1: --2017-05-22: command not found
/usr/local/bin/emojify: line 2: syntax error near unexpected token `('
/usr/local/bin/emojify: line 2: `Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.64.133, 151.101.192.133, 151.101.0.133, ...'

P.S-I'm using ubuntu 17.04

**Comment by SwampDolphin97** [comment]
Since I have wget instead of curl. I copied this 
**"sudo sh -c "wget https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o /usr/local/bin/emojify && chmod +x /usr/local/bin/emojify""** 
in my terminal. And then copied 
**"emojify "Hey, I just :raising_hand: you, and this is :scream: , but here's my :calling: , so :telephone_receiver: me, maybe?"".**
 Which is giving this **output.**
**/usr/local/bin/emojify: line 1: --2017-05-22: command not found
/usr/local/bin/emojify: line 2: syntax error near unexpected token (' /usr/local/bin/emojify: line 2:Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.64.133, 151.101.192.133, 151.101.0.133, ...'**

**Comment by GrenderG** [comment]
Can you check the contents of `/usr/local/bin/emojify`? I think you aren't downloading the file well. If you download it using `curl` or manually and then moving the file to `/usr/local/bin` it'll work. :smile:

What do you think @mrowa44?

**Comment by SwampDolphin97** [comment]
Fixed! 😊 You need to use curl it instead wget.

**Comment by GrenderG** [comment]
@SwampDolphin97 Perfect :smile_cat:
