### ISSUE TITLE
Git-Log graph color is not display with emojify

### ISSUE THREAD

**Issue by ooJerryLeeoo** [mrowa44/emojify#21]
For example:

`with emojify`

![screen shot 2017-06-28 at 16 12 29](https://user-images.githubusercontent.com/20783502/27626997-bd267e32-5c1c-11e7-8c43-f0baf0d08419.png)

`without emojify`

![screen shot 2017-06-28 at 16 12 43](https://user-images.githubusercontent.com/20783502/27627004-c56832c0-5c1c-11e7-9272-327a42c0aad6.png)

**Comment by mrowa44** [comment]
Weird, works on my machine. Can you give me more details, like what exact commands did you use etc.?
Works for me with:
```sh
git log --oneline --color --graph | emojify | less -r```

**Comment by ooJerryLeeoo** [comment]
@mrowa44 Oh, my bad, I forgot the `--color` flag, XD

**Comment by GrenderG** [comment]
@ooJerryLeeoo please, make sure to check everything twice before submitting an issue. :wink:
