### ISSUE TITLE
Handle punctuation chars

### ISSUE THREAD

**Issue by juergenhoetzel** [mrowa44/emojify#24]
Current  behaviour:
```
echo "Enter the :airplane:!" |./emojify 
Enter the :airplane:!
```

even though I don't see an easy solution to this (adding to `IFS`...)

**Comment by juergenhoetzel** [comment]
> even though I don't see an easy solution to this (adding to IFS...)

Maybe removing trailing punctuation chars of  current `word` in `parse_line` function?

**Comment by Heziode** [comment]
Hi, I've make a [binding in perl](https://github.com/Heziode/emojify) that solve this issue.

**Comment by WangGuibin** [comment]
Mac : command + control + space
