### ISSUE TITLE
Bash Completion

### ISSUE THREAD

**Issue by juergenhoetzel** [mrowa44/emojify#25]
Are you interested in including Bash-Completion for the `emojify` command?

https://gist.github.com/juergenhoetzel/83aa567601bbb8339366d265b5470364

**Comment by mrowa44** [comment]
Well, I don't know much about how something like this is done usually. Isn't it something that everyone can add on their own? Or is it common for packages such as this to include completion?

**Comment by juergenhoetzel** [comment]
Yes it doesn't have to be part of `emojify`.
