### ISSUE TITLE
I created a key binding for i3wm for getting an emojified string

### ISSUE THREAD

**Issue by lopis** [mrowa44/emojify#28]
I didn't know where to share this. This is for the i3 windows manager. It opens a small prompt where the user can type some text, then press Enter, and have the emojified text copied to their clipboard.

    bindsym $mod+shift+e exec i3-input -P 'emojify:' -F "exec emojify %s | tr -d '\n' | xclip -selection clipboard"

**Comment by mrowa44** [comment]
I think you can add a bullet point in readme in [related section](https://github.com/mrowa44/emojify#related) that links here
