### ISSUE TITLE
Support for ZSH shell

### ISSUE THREAD

**Issue by joshuawise610** [mrowa44/emojify#32]
I downloaded the emojify script and modified the script such that the shebang is `!/bin/zsh` to execute using the zsh shell and changed out the `{BASH_VERSION}` environment variable for `{ZSH_VERSION}`.
Upon running the script using `emojify :joy` I get output:
```
emojify.sh:25: no matches found: [:grinning:]=\U1f600
parse_line:1: bad option: -a
to_emoji:1: bad math expression: empty string
```
This message comes up every time I try running the script regardless of what text I enter.
I'm aware that zsh can support basic emoji using the emoji plugin from oh_my_zsh which I have enabled, but I am unable to work out what this error message means.

**Comment by filipekiss** [comment]
You don't need to make any changes to have this working on ZSH. In fact, the bash version is the problem. If you're using macOS and [homebrew], just `brew install bash` and emojify should work without problems. If you're on linux, just google `<your distro name> upgrade bash` to see how to upgrade bash. :)

[homebrew]: https://brew/sh

**Comment by filipekiss** [comment]
@scrunch077 I've ported this to be native to Zsh, check it out: [filipekiss/zemojify]

[filipekiss/zemojify]: https://github.com/filipekiss/zemojify

**Comment by joshuawise610** [comment]
@filipekiss Sorry for taking so long to get back to you, the zemojify port you made works perfectly on my system. Thanks for your help.
