### ISSUE TITLE
add package to brew

### ISSUE THREAD

**Issue by lifeiscontent** [mrowa44/emojify#6]
since I'm not the maintainer, I'm unsure if I should do it.

**Comment by mrowa44** [comment]
Sure, but I have to release it first, right?

**Comment by lifeiscontent** [comment]
:+1:

**Comment by mrowa44** [comment]
Hey, I released it some time ago. In case you didn't notice that :blush:

**Comment by johnhampton** [comment]
I created a formula and submitted a PR for homebrew (homebrew/homebrew-core#1607).

**Comment by mrowa44** [comment]
Thanks a lot! 😸  I noticed it was already merged so I mentioned it in readme 🎉

**Comment by Pustur** [comment]
The version on homebrew is outdated (`1.0.2`)  
Would you consider updating it?

`$ brew info emojify`

```
emojify: stable 1.0.2, HEAD
Emoji on the command-line :scream:
https://github.com/mrowa44/emojify
/usr/local/Cellar/emojify/1.0.2 (5 files, 44.6KB) *
  Built from source on 2019-10-09 at 16:09:57
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/emojify.rb
License: MIT
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 62 (30 days), 174 (90 days), 814 (365 days)
install-on-request: 62 (30 days), 174 (90 days), 816 (365 days)
build-error: 0 (30 days)
```
