### ISSUE TITLE
Spaces following emoji on OS X

### ISSUE THREAD

**Issue by shawnyeager** [mrowa44/emojify#7]
Great script. It appears that trailing spaces are being stripped or otherwise not displaying on OS X. Here's a screen shot using iTerm 2, but I've tried it with the built-in Terminal as well; same result. I'm running OS X 10.10.5

![screenshot 2015-07-31 09 06 08](https://cloud.githubusercontent.com/assets/980297/9009008/cc3ea6cc-3763-11e5-881e-b26da5c16f66.png)

**Comment by eugenekolo** [comment]
Are you sure it's not the font? And not OSX? The space is actually there, not stripped. They just are underneath half of the emoji.

**Comment by kergoth** [comment]
Whitespace is definitely being screwed up on osx:

```
💯 foo

   Signed-off-by: Christopher Larson <kergoth@gmail.com>
```

Note the lack of indentation on the :100: line in my git log.

**Comment by CaptainQuirk** [comment]
Tried the example of @shawnyeager and added up to 10 spaces after and before the emoji tag. Everything gets stripped.
Must be related to the line splitting operation that removes additional spaces.

**Comment by posva** [comment]
ATM the script just strips off all extra whitespace.
Is there any intention in fixing this?
I'm using https://github.com/as-cii/terminal-emojify in the meanwhile

**Comment by GrenderG** [comment]
Happening on GNU/Linux (Ubuntu 16.04) too.

**Comment by GrenderG** [comment]
This issue has been solved [here](https://github.com/mrowa44/emojify/pull/15).
